import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import ReactQueryProviders from './hooks/useReactQuery'
import HeaderNavigationBar from './component/HeaderNavigation/HeaderNavigationBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProviders>
          <div id="root" className="pt-14">
            <HeaderNavigationBar />
            {children}
          </div>
        </ReactQueryProviders>
      </body>
    </html>
  )
}
